### ISSUE TITLE
Hi please tell me VTK version is ????

### ISSUE THREAD

**Issue by jfjfjf8888** [UCL/BernabeuInterface2014#1]
VTKLIB-5.10.0 compile error

**Comment by myousefi2016** [comment]
The VTK version should be < 6 but you don't need to compile it from scratch. I assume you have access to some UNIX machine and as a result, you should be able to install it by using this command:

Ubuntu:

`sudo apt-get install libvtk5-dev`

**Comment by mobernabeu** [comment]
We've made a GUI to run the MATLAB scripts in this repo and packaged it up with Docker so you won't need to worry about dependencies.

Take a look at this paper: https://www.cell.com/biophysj/fulltext/S0006-3495(18)30438-7
